
[params.product_version.chef-server]
versions = ["13_2", "14_0"]

# set the base file path used for "Edit on GitHub links"
[params.gh.chef-server]
path = "https://github.com/chef/chef-server/blob/master/docs-chef-io/content/"


####
# Chef Infra Server Menu
####

[[menu.server]]
title = "Chef Infra Server"
identifier = "server"

  [[menu.server]]
  title = "Overview"
  identifier = "server/overview"
  parent = "server"
  weight = 10

  [[menu.server]]
  title = "Planning"
  identifier = "server/planning"
  parent = "server"
  weight = 20

  [[menu.server]]
  title = "Installation"
  identifier = "server/installation"
  parent = "server"
  weight = 30

    [[menu.server]]
    title = "Airgap"
    identifier = "server/installation/Airgap"
    parent = "server/installation"
    URL = "/install_chef_air_gap/#chef-infra-server"
    weight = 30

    [[menu.server]]
    title = "Hosted Chef Server"
    identifier = "server/installation/Hosted Chef Server"
    parent = "server/installation"
    URL = "https://manage.chef.io/signup"
    weight = 40

  [[menu.server]]
  title = "Configure"
  identifier = "server/configure"
  parent = "server"
  weight = 40

    [[menu.server]]
    title = "Server Firewalls and Ports"
    identifier = "server/configure/Server Firewalls and Ports"
    parent = "server/configure"
    URL = "/server/server_firewalls_and_ports/"
    weight = 40

  [[menu.server]]
  title = "Manage"
  identifier = "server/manage"
  parent = "server"
  weight = 50

  [[menu.server]]
  title = "Reference"
  identifier = "server/reference"
  parent = "server"
  weight = 60

####
# End Chef Infra Server Menu
####
